USE [master]
GO

/****** Object:  Database [GreenCarpetsDb]    Script Date: 16/08/2021 6:39:59 pm ******/
DROP DATABASE [GreenCarpetsDb]
GO

/****** Object:  Database [GreenCarpetsDb]    Script Date: 16/08/2021 6:39:59 pm ******/
CREATE DATABASE [GreenCarpetsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreenCarpetsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\GreenCarpetsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GreenCarpetsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\GreenCarpetsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreenCarpetsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GreenCarpetsDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GreenCarpetsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GreenCarpetsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GreenCarpetsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GreenCarpetsDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET RECOVERY FULL 
GO

ALTER DATABASE [GreenCarpetsDb] SET  MULTI_USER 
GO

ALTER DATABASE [GreenCarpetsDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GreenCarpetsDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GreenCarpetsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GreenCarpetsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GreenCarpetsDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GreenCarpetsDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GreenCarpetsDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GreenCarpetsDb] SET  READ_WRITE 
GO


