export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT :"REMOVE_SELECTED_PRODUCT",
    SET_CART : "SET_CART",
    TOTAL_CART_ITEMS:"TOTAL_CART_ITEMS",
    ADD_TO_CART :"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREASE_QUANTITY :"INCREASE_QUANTITY",
    DECREASE_QUANTITY:"DECREASE_QUANTITY",
    DELETE_CART:"DELETE_CART",    
    USER_LOGGED_IN:"USER_LOGGED_IN",
    USER_LOGGED_OUT:"USER_LOGGED_OUT"
};